export type ThoughtStage =
  | "expand"
  | "clarify"
  | "question"
  | "recall"
  | "structure"
  | "organize"
  | "map"
  | "analyze"
  | "reason"
  | "compare"
  | "evaluate"
  | "decide"
  | "approve"
  | "reject"
  | "hold"
  | "warn"
  | "apply"
  | "implement"
  | "test"
  | "fix"
  | "summarize"
  | "conclude"
  | "reflect"
  | "next"
  | "blocked"
  | "skip"
  | "stop"
  | "analyzing_image";

export const emojiMap: Record<ThoughtStage, string> = {
  expand: "🤔",
  clarify: "🔍",
  question: "❓",
  recall: "🧠",
  structure: "🧩",
  organize: "🗂️",
  map: "🗺️",
  analyze: "📊",
  reason: "🧠",
  compare: "⚖️",
  evaluate: "🧪",
  decide: "✅",
  approve: "👍",
  reject: "❌",
  hold: "✋",
  warn: "⚠️",
  apply: "🛠️",
  implement: "👆",
  test: "🧪",
  fix: "🩹",
  summarize: "✨",
  conclude: "🏁",
  reflect: "🪞",
  next: "👉",
  blocked: "🚫",
  skip: "⏭️",
  stop: "🛑",
  analyzing_image: "🖼️",
};
